twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
        app_name: "Project Name"
        reset_password_form: '@App\Service\ResetPassword'
        admins: '@App\Repository\UserRepository'
